### ISSUE TITLE
BranLWIll Final Project Proposal 

### ISSUE THREAD

**Issue by BranLWill** [valencia-cop1000-201620/final-project#23]
### Name
Brandon Willett

### Proposed Project Description
For my final project I am going to be creating a connect four game with an A.I. It would be similar to the tic tac toe board game that we created but the player will be playing a computer. The board would be similar and the pieces for the game would be represented as X's for red and O's for blue.

What color would you like to be?
Type X for Red or O for Blue.

You are Red(X)
The computer is Blue(O)

Choose your spot.
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + + + +
+ + + + + + + 
+ + + + + + + 

your turn
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + + + +
+ + + + + + + 
+ + + + + X + 

Computers turn
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + + + +
+ + + + + + + 
+ + + + O X + 

your turn
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + + + +
+ + + + + X + 
+ + + + O X +

computers turn
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + + + +
+ + + + O X + 
+ + + + O X +

your turn
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + + X +
+ + + + O X + 
+ + + + O X +

computers turn
+ + + + + + +
+ + + + + + + 
+ + + + + + + 
+ + + + O X +
+ + + + O X + 
+ + + + O X +

your turn
+ + + + + + +
+ + + + + + + 
+ + + + + X + 
+ + + + O X +
+ + + + O X + 
+ + + + O X +

Player Red win/you win

In order for you to win in connect four you have to get four of your pieces in a row to win, its the same concept as tic tac toe but in a bigger scale.
  
### Connecting Concepts
My program would cover chapters 1-4

### Timing
I can complete it by Wednesday the 27th

### Asking for...
Any ideas to help will be welcomed.

**Comment by halfaro1** [comment]
@BranLWill thanks for the proposal! Could you please post a little more detail of how this works? Not everyone might have played Connect Four, or their gameplay might be different than what you're proposing. It would help if you post a simulated gameplay between user and computer, or a few diagrams showing how the board would look through different states in the game.

**Comment by BranLWill** [comment]
@halfaro1 I think i am going to change my proposal to a text based adventure game but the story and setting of my adventure game will be different then the other one that is doing a text based adventure game I think they are doing a horror game and I'm doing an adventure game in space. Is this alright?

**Comment by BranLWill** [comment]
@halfaro1 I just think that i do not have enough time to create a connect four game. by wed

**Comment by halfaro1** [comment]
@BranLWill I'd like to work with you on the Connect Four game. I think it's a unique and original idea. I think I have a suggestion that'll allow you to get this done in the time you have as opposed to starting brand new. You should also continue to work on this even if you're waiting for me or a classmate to reply. You can move forward with designs, pseudocode, diagrams, research, etc.

My suggestion would be to iterate on your tic tac toe game. You can start with the version of tic tac toe you created for your project and modify it so that the payer chooses a column, and not a specific spot on the board. Just like in Connect Four, where the player would choose a column to place their piece in. Most other things should be the same (the players take turns, the winning conditions are the same as in tic tac toe). The only difference is that the player chooses a column instead of a specific spot, and the program has to know to place the piece at the lowest possible spot on that column. Does that make sense?

If you can get that version I described above to work, you can then make a new version that creates a 6x6 board instead of the 3x3 board of Tic Tac Toe (but only if you get the 3x3 version working).

**Comment by BranLWill** [comment]
@halfaro1 Alright, I understand what you are saying but the only part that i was having trouble with was the running part i had the board all set up and i was trying to run it to test if i did the board properly but it just auto restarts the shell. So if you have any suggestions on how i can properly run it for testing purposes would be greatly appreciated?

**Comment by BranLWill** [comment]
@halfaro1 I have it working, awesome! But i want to upgrade it a bit more so ill continue on it and i should have a finished product by wed

**Comment by BranLWill** [comment]
@halfaro1 I am close to finishing with my connect four game and i was wondering do i need to be approved to upload it to the pull request or could i just upload it. If i need to be approved first, could you let me know what i have to do to get approved.

**Comment by halfaro1** [comment]
@BranLWill yikes, it looks like I missed your comments here from 3 days ago. I'm so sorry about that -- my fault not yours. I've reopened your pull request. I'm not sure if the questions you were asking here are still things that are giving you trouble so if they are feel free to ask over in the pull request #65

**Comment by halfaro1** [comment]
@BranLWill I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
