### ISSUE TITLE
John's final project

### ISSUE THREAD

**Issue by JohnSwain117** [valencia-cop1000-201620/final-project#24]
### Name
John Swain

### Proposed Project Description
Turtle is a built in graphics program in python that utilizes different commands to manipulate screen size, color, etc while allowing you to display text and draw sketches with simple commands like 
**turtle.forward()** **turtle.left()** inside the parenthesis you would put the distance or angle.
I will explain more commands and how to use them inside the program im making.

This program will be multi layered with 2 or 3 callback functions so users can go back to a "main menu" of sorts that will allow them to change what they are looking at. It will have approximately 3 or 4 sections, 1 for a basic explanation as to what turtle is, 1 for explaining turtle commands and what they do, 1 for teaching the user how to implement said commands into a program, and a final one that would display examples of what turtle can do as well as show example codes. I may add a 5th section that is solely example codes for different things such as squares or Spirograph.

### Connecting Concepts
I would ask the user what they wanted to do, use random to construct different images in turtle, and use what we learned in the manipulating images unit.

### Timing
I would be using a combination of images I have made and images I got off the internet, as well as the python turtle images. If approved I could probably have it done by the 26, 27th at the latest.

### Asking for...
I was wondering what kind of things I should add or change as well as what kinds of pictures I should use. Thank you all ahead of time.

### Turtle Walk through
When I said turtle walk through I was thinking of a more basic program that asked the user what they wanted to know. It would include an introduction to explain what turtle is, an explanation of how it differs to a normal program (display commands, color, shapes, text, etc.) and how to start using it. It would also come with options to preview art such as a sketch of a house (including driveway, sidewalk, maybe a tree and bush), an option that shows example code of shapes and then asks if you would like a demonstration, some random generations and a Spirograph.

**Comment by halfaro1** [comment]
@JohnSwain117 thanks for the proposal! It looks like there's 2 different ideas in your proposal? I'm not sure how they link to one another (they're distinct to me). I ❤️ the Python Turtle idea. I don't think it's something other people may have seen (or if they've seen it, they may not have implemented it). So this would be a unique thing to implement. I also like the fact that it's a walkthrough since it's not just a program that shows something, but a program that *teaches* someone something. I'd encourage you to break down that idea a little further and explain it in more detail for us, and then I'll be ready to 👍

**Comment by elicegreen** [comment]
I had to google 'python turtle' to know what you're talking about. 
Maybe add a short description of what it is, just the fact that it's a graphic tool even?
I'm not sure if you're going to implement this as I see that you've closed and then re-opened this.
If you do go ahead with this, I will absolutely love to check it out. It sounds really cool!
I think that by focusing on coding just a sort of a walk through makes your project reasonable for the time frame for implementation, especially since you've mentioned that you already have gathered some images that you'll use.

**Comment by halfaro1** [comment]
@JohnSwain117 how are you doing on this description? I'd like you to move forward as soon as possible since you only have a few days.

**Comment by JohnSwain117** [comment]
I'm sorry for not explaining in more detail and I thought that by closing and reopening the issue it would move to the top of the list, anyway I was gone all of yesterday at a family event, I have been steadily working on the project and believe it can be finished by the 27 at most.

**Comment by halfaro1** [comment]
@JohnSwain117 I'm still looking for you to break down the idea here -- there is an open proposal still that hasn't been approved. I'm happy to approve it as long as I have the detailed we discussed.

**Comment by JohnSwain117** [comment]
Im not sure exactly what you want me to add but I will be posting what I have done of my Project, Its a bit of a mess and Im gonna work on commenting it and cleaning it up tomorrow.

**Comment by halfaro1** [comment]
@JohnSwain117 did you edit your original post? that's the kind of description I was looking for.

**Comment by JohnSwain117** [comment]
OHHHH my bad yes I did edit the original post I didn't even pickup on that being what you meant. My bad.

**Comment by halfaro1** [comment]
@JohnSwain117 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
