### ISSUE TITLE
msegura final project proposal

### ISSUE THREAD

**Issue by MarcialSegura** [valencia-cop1000-201620/final-project#33]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Marcial Segura 

### Proposed Project Description
So I was thinking about doing a Star Wars Quiz, kind of like how much do you know about Star Wars. I first thought about a "What Kind of Jedi are you?" But I think I want to stick to True and False coding so it makes it easier. The quiz would be as simple as "How many Star Wars movies are their?" or "What planet did Darth Sidious destroy with the Death Star?" the questions would probably be easier than that at the end, and the quiz would just give you a value of how much of a nerd you are :). 

### Connecting Concepts
It will cover some of the basics of Python. Also, path flow, user input, variables and maybe list. 

### Timing
4/20/16: Approve date
4/21/16 - 4/24/16: Have a daft of the code
4/25/16 - 4/26/16: Work out the rough edges and test code
4/27/16: Submit 

### Asking for...
Should I stick to using True or False? I tried to keep this project super simple and not over complete it.

**Comment by halfaro1** [comment]
@MarcialSegura I like it! I'd like to see what other classmates have to say for feedback. I do think you need to decide on true/false, multiple choice, or open response before you start implementing. While you're waiting for feedback and approval, please start coming up with a list of questions you'll use so that you can start fleshing out this idea, and also come up with the 'nerd' scoring system :) ⭐

**Comment by Nate388** [comment]
Trick question. Palpatine never destroyed any planets with the Death Star, only Grand Moff Tarkin ordered the destruction of Alderaan. However during the battle of Endor, Palpatine did order to fire on the rebel fleet destroying an MC80 Star cruiser...

Also How many questions do you plan on asking, and would that affect the difficulty of the questions? 
Like for instance if I were going to add only say 10 questions, I would make them slightly difficult and obscure just because there's only a few questions and I wouldn't want my test takers to breeze through it.

**Comment by jmendez50** [comment]
So what movies will this go into? Will it be them all or are we just sticking with the originals?

**Comment by halfaro1** [comment]
Super relevant 


![](http://i.imgur.com/67pkfOF.gif)

**Comment by halfaro1** [comment]
@MarcialSegura how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by nickivey2** [comment]
I like this idea, you could easily turn this into a mobile application porting this to Swift or Java for android.

**Comment by MarcialSegura** [comment]
Super sorry for the late replay! 

@jmendez50 I wanted to focus on just moives 1-6 figuered that most people have seen those. 

I wanted to stay away from super obscure material such as the books, video games, etc. I know I could've gone more elaborate with the questions, but that wouldve opened up the flood gates on the coding. At this point I did about 8 questions and it's pretty easy to past it.

**Comment by halfaro1** [comment]
@MarcialSegura so what questions are you going to use? and what are all the responses? this was due last night and was extended until tonight. Make sure you get this approved (that's half your grade) and get whatever code you have in by the end of tonight (that's the other half of your grade).

**Comment by MarcialSegura** [comment]
@halfaro1 Some questions I used were, "Could Jedi's have realationships outside of thier normal duty's?" and then the user would input either T (True) or F (False). If answered right, you'll move on to the next quesion and answer again with T or F.

**Comment by halfaro1** [comment]
@MarcialSegura I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Comment by halfaro1** [comment]
Grading final project based on: https://github.com/MarcialSegura/Final-Project-
