### ISSUE TITLE
ukates Final Project Proposal

### ISSUE THREAD

**Issue by ukates** [valencia-cop1000-201620/final-project#44]
Derrick Cates

### Proposed Project Description
Recently I got a new car, so I felt this would be a really useful program for me and hopefully I build it well.  I plan on paying it off as quickly as possible so that I can pay the smallest amount of interest possible.  I would like to make an auto loan payoff calculator. Basically the loan calculator will ask the user the total loan amount, the interest rate, and the length of the loan.  You would be able to change the length of the loan to whatever you would like the payoff length to be.  

Once you put in that information the calculator will determine the total cost of the car loan with interest that you would have paid over the course of the payoff length, and the amount that you would need to pay each month in order to pay off the loan in that amount of time.  It will also provide feedback if the user does not input the data correctly asking them to try again until it is correct. 

The problem I have with calculators is that i find myself going in and out of them constantly because I fail to remember the results, it would be nice to have this program create a .txt document and save it to my auto loan documents folder so that I could always check there, without having to run the program over and over if my inputs have not changed.  It would be really cool if i could have it update my payment date on my calendar to add a note of what the payment should be for the month, but not sure how I would implement that so i probably shouldn't even tackle that. 

### Connecting Concepts
This program will cover Flow control from chapter 2 /  Functions and def statements from chapter 3 / since I would like for it to make a text document for me it will also cover reading and writing files from chapter 8 and organization from chapter 9 because of saving it to my auto documents folder. 

### Timing
I am fairly slow at this right now and also work full time, so I would say that it will take a few days for me.  The first thing I will complete is just the portion of the program that actually calculates the data.  After I get that displaying properly in the program, I will work out how to create the .txt and save it to the designated folder to help me remember! 

### Asking for...
Any feedback would be helpful, honestly not sure what type of feedback I am looking for, any way that you could see to make the program more interesting would be helpful, but I chose this because it applies to my current situation.

**Comment by halfaro1** [comment]
@ukates great project! I love ideas that are practical and that are also your own because I think you'll get much more out of it than a random project I throw at you. My suggestion is to keep it simple. Start with a simple loan calculator with just the loan payoff amount. I think you'll be able to do this fairly easily, actually. A version 2 (in your case, I recommend you strive to get to version 2 at least) would be to include calculation of a payoff date based on that information. A version 3 (not required, but if you get to it great) could include the exporting to TXT and calendar entry you described. 

Before I approve, I'd just like you to think about the math behind the program. How will you calculate loan payoff and the payoff date? Also think about the Python libraries that could help you with date calculations like what we're suggesting here.

**Comment by aeuteneuer** [comment]
Derrick,
This is an awesome idea! I don't really have any recommendation because I like this and think it will be great however I have an idea for a version 2.0. Maybe if you were to take this to another level and also include maybe house payments and or other payments that people pay off over time. Just something to think about.

**Comment by smoussadeq** [comment]
Derrick, 
This is sound like a really good project. It look like a complex project though. So, my only suggestion for you, and as the professor said, make sure to simplify it as much as possible. 
Good luck and looking forward to see the final project 👍

**Comment by ukates** [comment]
@halfaro1 when it comes to determining the payoff / monthly rate my program is going to ask for the information to complete a basic auto loan monthly payment formula.  monthly payment = loan amount * (interest rate per month ( 1 + interest rate per month)*pow(life of loan))) / ((1+interest rate per month)*pow(live of the loan)) - 1) 

This should give me the monthly payment rate interest included.  i can calculate the total payoff balance by just taking the monthly rate multiplied by the life of the loan correct?   To help me with determining the payoff date based on the information the user will input into the program i believe ill need to import the datetime module is that correct?

**Comment by halfaro1** [comment]
@ukates [this whole page](https://pymotw.com/2/datetime/) might be helpful, but particularly [this section](https://pymotw.com/2/datetime/#date-arithmetic).

**Comment by mviruet2** [comment]
This project it is gonna be so helpful, because we can use it for more than a car loan. I'm looking forward to use it. It would be great if it could create an excel document with all the information.

**Comment by halfaro1** [comment]
@ukates I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
