### ISSUE TITLE
Lamle104: Final Project Proposal

### ISSUE THREAD

**Issue by Lamle104** [valencia-cop1000-201620/final-project#5]
### Name
Lam Le

### Proposed Project Description
Something that I would like to do for my final project would be a reminder of the birthdays of my best friends and what I plan on getting them. This program tells me the names and dates of my best friends. It also includes what I plan on getting them on their birthdays. The program limits the program to ONLY remember birthdays/gifts while its running. If their birthdays aren't in the database then the user can enter the date. 

### Connecting Concepts
This project covers chapter 5 dictionaries and chapter 2 flow control statements.

### Timing
Project may take a few hours or a day. 

### Asking for...
Just some positive feedback and ways to enhance this program.

**Comment by xyngabo** [comment]
The program is always running and reminds you when the date approaches or you run the program whenever you are curious and it tells you everyone's birthday or maybe just the birthdays that are soon?

**Comment by Lamle104** [comment]
When you feel like a birthday is coming up but you're not sure the exact date. :D @xyngabo

**Comment by cholbrook2** [comment]
So you'll make it to where it will store the birthday with the name? That's a neat idea.

**Comment by elisenharper** [comment]
This sounds really handy! I tend to forget dates :)

**Comment by ryby6969** [comment]
This might make a nice free app.

**Comment by AbigailAndersonn** [comment]
We did have very similar ideas! Great minds think alike, hah. Or, great minds forget peoples birthdays. :P
The gift reminder would be really useful for me as well. Since I tend to forget birthdays, I usually don't even realize I need to GET a gift till the last minute. I guess I'm lucky I'm very crafty, it's the thought that counts, right? haha

**Comment by mmarchetti2** [comment]
It'd be cool if you could make a way to easily alter the list at any time. Also, if you can find out how to do it, you could get it to send you a notification when a birthday is nearby. The idea itself is a great one, and I hope you can pull it off in time. Good luck! :D

**Comment by halfaro1** [comment]
@Lamle104 good start. But you're going to have to think of a way to store those birthdays after the program quits. Otherwise, every time the program starts it will not remember the last birthdays you entered. You could store this information in a file (see the chapter on manipulating files). Take a look at it and let me us know if it's something you're thinking about continuing to implement or if you'd like to modify it a bit. Another option is to do something similar to what @xyngabo suggested which is to limit the program to only remember birthdays/gifts while it's running so that you don't have to worry about saving that information in a file. Let me know your thoughts.

**Comment by Lamle104** [comment]
I think im going to go with what @xyngabo suggested. Limit the program to only remember birthdays/gifts while its running. But I'll take a look at the manipulating files as well. @halfaro1

**Comment by halfaro1** [comment]
@Lamle104 perfect! could you please modify your original post to show that? also add a simulated interaction between the user and the program to the original post and then I'll be ready to approve.

**Comment by nhatnam113** [comment]
Great post bro! I think your best friends will never forget your birthday with this great reminder

**Comment by Lamle104** [comment]
Modified my original post @halfaro1 . :)

**Comment by Lamle104** [comment]
what do you mean by simulated interaction? @halfaro1

**Comment by halfaro1** [comment]
@Lamle104 show what the screen would say when your program launches, what the user would then type, and what your program would do in response, and so on.

**Comment by Lamle104** [comment]
Hows that? @halfaro1

**Comment by halfaro1** [comment]
I'm not sure what you're asking @Lamle104. Feel free to reach out via Gitter if you have a particular question. However, you should be posting here, in text, a simulation of how the program would work from the user's perspective.

**Comment by Lamle104** [comment]
When the program launches it would say something like "Enter your friends name here." You would then proceed to enter your friends name and it will provide you with what your friends birthday is and what you plan on getting them. If your friends birthday isn't in the database then the program will then ask you when their birthday is and store their birthday in the database.

**Comment by halfaro1** [comment]
@Lamle104 thanks, this is approved.

**Comment by halfaro1** [comment]
@Lamle104 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
