### ISSUE TITLE
cholbrook2 Final Project Proposal

### ISSUE THREAD

**Issue by cholbrook2** [valencia-cop1000-201620/final-project#7]
**### Name**
Chelsea Holbrook

### Proposed Project Description
I would like to create a random restaurant generator. This is something I have always wished was simple to find on the internet, where all of them that I find are either just fast food or places that are not near me. I feel this could end a lot of the "Where would you like to eat?" "I don't know" conversations much quicker.
A sample interaction of this program would be "What type of food would you be in the mood for?" where there would be list values of "American, Chinese, Italian, etc." For simplicity purposes, I will use a set list of restaurants in a specific area code (most likely central Orlando for a larger number of option possibilities). Depending on the input, the program will generate a random option from a list/dictionary of places to eat from the specific type of place selected, like Olive Garden, Carrabba's, and mostly smaller chains that I have never been to but sound interesting :) 

### Connecting Concepts
Chapters 2-7 will most likely all be utilized in this project.

### Timing
I will be able to get this done within a few days surrounding work and other course work I will be doing. The basic outline of the functions and lists should be done by tomorrow, which will then be ready for nitpicking at the types of food and possible restaurants.

### Asking for...
Honestly any suggestions on being able to draw a Google Maps search for restaurants in the area of a specific zip code from the program (or even a simpler idea) would be very helpful. Otherwise, any feedback would be fantastic!

**Comment by xyngabo** [comment]
https://www.google.com/maps/search/resturants+34758/

**Comment by xyngabo** [comment]
https://www.google.com/maps/search/resturants+34758/

**Comment by elisenharper** [comment]
I had a very similar idea back when we did the random number project. I always thought of how annoying it is to try to figure out what's for dinner. I was thinking of making this my final project and then having it suggest certain types of food (Italian, burgers, pizza...etc) then suggesting restaurants nearby.

**Comment by Lamle104** [comment]
Very good idea and I feel that this could come in handy for a lot of people!

**Comment by ryby6969** [comment]
I think this would be something that would be a nice base and you would be able to build on it.

**Comment by AbigailAndersonn** [comment]
I had an app on my phone a while back that would find restaurants by regional/types of cuisine. It had everything from basic options like pizza & sports bars, to French and various uncommon options like Icelandic and Nepali. Obviously, actual results all depend on the establishments in your area. 

I loved the concept and long story short, I think this is a great and very useful program idea. Have you considered incorporating Yelp? The search engine seems to accept and even predict/suggest almost anything you can think of. I think it might be useful because it also provides a lot of info and actually includes the Google map.

**Comment by cholbrook2** [comment]
Thank you, everyone! 
@AbigailAndersonn That's an awesome idea

**Comment by halfaro1** [comment]
@cholbrook2 cool idea! you're on the right track and I understand your concern with having to learn how to integrate with Google Maps. For this particular use, you'd use what's known as an API (Application Program Interface). An API is a set of functions that a software company gives you to interact with their software. They are covered in [Chapter 14](https://automatetheboringstuff.com/chapter14/). Some API's that may be of interest to you are:
* [Google API](https://developers.google.com/maps/)
* [Yelp API](https://www.yelp.com/developers)

I'm all for letting you explore APIs if you'd like to for this final project, but if you want to do that I'd simplify the heck out of it so that the task is very simple and straightforward since you'll be spending much of your time figuring out how to use the API.

If you decide not to use the API, you can still create a "first draft" by building the rest of the program, and (for now) leaving the part where the program goes out to fetch something from the web out -- so it would be a program that always uses the same list of static restaurants and we'd represent everything internally.

Let me know what route you'd like to go and we can take it from there.

**Comment by cholbrook2** [comment]
@halfaro1 I did some looking at the API process, that may be something I will look into when I am not working within a time frame. For this final project, a static list is sounding to be more friendly

**Comment by halfaro1** [comment]
@cholbrook2 awesome! Then please edit your original post with the modified idea, and include a sample listing of restaurants and zip codes (or however you'll structure the data) and a simulated interaction between the user and the program. When that's there, we'll be ready for a 👍

**Comment by BranLWill** [comment]
This sounds awesome! Would it be like those apps or more text based?

**Comment by cholbrook2** [comment]
Okay @halfaro1 all changed!

@BranLWill definitely more text based for the sake of the time given!

**Comment by halfaro1** [comment]
@cholbrook2 good to go, please make sure you include the list of restaurants by type of food in your design.

**Comment by halfaro1** [comment]
@cholbrook2 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
