### ISSUE TITLE
jsavon's Final Project Proposal

### ISSUE THREAD

**Issue by jsavon** [valencia-cop1000-201620/final-project#85]
### Name
Joshua Savon

### Proposed Project Description
This is going to be a simple dice rolling program. You will be rolling a six sided die (1-6) and the program will pick a random number for you. The program will then print out the random number. You will be able to roll the die over and over again.

At the moment the dice will show up as: (Doesn't look good here for some reason)
You rolled a five!
  [-------------]
  [   O   O    ]
  [      O       ]
  [   O   O    ]
  [-------------]
### Connecting Concepts
This program will help me practice with Integers, working with random answers, and printing out responses. More specifically from chapters 2-3

### Timing
This project will be completed in no more than 24 hours.

### Asking for...
I will ask if there is anything else i should add to the program. Is it too simple or is it the right amount.

**Comment by halfaro1** [comment]
@jsavon what does your program design look like? how will you structure the code? some things I'd like to know before approving are: does your program use functions? it should. what functions? will it do anything to show the dice, such as creating ASCII art? as it's described it's not complex enough to be a final project, but since you're short on time it may be to your advantage to do this instead of nothing at all. I want to know your thoughts so please feel free to let me know here.

**Comment by Tchomp** [comment]
This project idea seems like a good idea to reflect on some principles. Good luck on the project Jsav!

**Comment by halfaro1** [comment]
@jsavon I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
